name: config-secrets

configuration:
  environment: production
  version: '1.0.0'

databases:
  db1:
    connection:
      host: localhost
      port: 3306
      database_name: db1_name
    options:
      timeout: 30
      retries: 3

  db2:
    connection:
      host: localhost
      port: 3307
      database_name: db2_name
    options:
      timeout: 20
      retries: 2

services:
  service1:
    endpoints:
      api:
        - endpoint: /api/endpoint1
          methods: [GET, POST]
        - endpoint: /api/endpoint2
          methods: [GET]

  service2:
    endpoints:
      api:
        - endpoint: /api/endpoint3
          methods: [GET, POST]
        - endpoint: /api/endpoint4
          methods: [POST]
