name: Unit Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pytest with coverage
        run: |
          poetry run pytest --cov=secured --cov-report term-missing tests/

      - name: Generate coverage report
        run: |
          poetry run pytest --cov=secured --cov-report=xml:coverage.xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
